//! Integration helpers for bevy-sculpter mesh generation.

use bevy::{mesh::VertexAttributeValues, prelude::*};
use bevy_sculpter::prelude::*;

use super::{
    MaterialBlendSettings, MaterialField, NeighborMaterialFields, compute_vertex_materials,
};
use crate::mesh::{MeshTriplanarExt, VertexMaterialData};

/// Extension trait for applying material attributes to meshes generated by bevy-sculpter.
pub trait MeshMaterialIntegration {
    /// Add triplanar material vertex attributes based on density and material fields.
    ///
    /// This computes per-vertex material blending based on the surrounding voxels'
    /// density values (how "inside" they are) and their material IDs.
    ///
    /// # Arguments
    /// * `mesh_size` - Size of the mesh in voxels (usually FIELD_SIZE as Vec3)
    /// * `density_field` - SDF density values (from bevy-sculpter)
    /// * `material_field` - Material IDs for each voxel
    /// * `neighbor_densities` - Optional neighbor density data for seamless boundaries
    /// * `neighbor_materials` - Optional neighbor material data for seamless boundaries
    /// * `settings` - Blend settings controlling how materials are weighted
    fn with_triplanar_voxel_materials<D: Field<f32>>(
        self,
        mesh_size: Vec3,
        density_field: &D,
        material_field: &MaterialField,
        neighbor_densities: Option<&NeighborFields<f32>>,
        neighbor_materials: Option<&NeighborMaterialFields>,
        settings: &MaterialBlendSettings,
    ) -> Self;
}

impl MeshMaterialIntegration for Mesh {
    fn with_triplanar_voxel_materials<D: Field<f32>>(
        mut self,
        mesh_size: Vec3,
        density_field: &D,
        material_field: &MaterialField,
        neighbor_densities: Option<&NeighborFields<f32>>,
        neighbor_materials: Option<&NeighborMaterialFields>,
        settings: &MaterialBlendSettings,
    ) -> Self {
        let Some(VertexAttributeValues::Float32x3(positions)) =
            self.attribute(Mesh::ATTRIBUTE_POSITION)
        else {
            return self;
        };

        let material_data: Vec<VertexMaterialData> = positions
            .iter()
            .map(|&pos| {
                compute_vertex_materials(
                    Vec3::from(pos),
                    mesh_size,
                    density_field,
                    material_field,
                    neighbor_densities,
                    neighbor_materials,
                    settings,
                )
            })
            .collect();

        self.with_triplanar_materials(&material_data)
    }
}

/// Bundle for spawning a chunk with material field generation.
#[derive(Bundle)]
pub struct MaterialFieldBundle {
    pub field: MaterialField,
    pub neighbors: NeighborMaterialFields,
}

impl Default for MaterialFieldBundle {
    fn default() -> Self {
        Self {
            field: MaterialField::new(),
            neighbors: NeighborMaterialFields::default(),
        }
    }
}
